# Site settings
title: Matthew Waliman
email: mwaliman@ucla.edu
description: > # this means to ignore newlines until "baseurl:"
   Electrical and Computer Engineering M.S. student at UCLA. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "mwaliman.me" # the base hostname & protocol for your site
production_url: "https://www.mwaliman.me"
github_username: mwaliman
permalink: /blog/:year/:month/:title.html

twitter:
  username: domoritz

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
